### ISSUE TITLE
bert 版本问题

### ISSUE THREAD

**Issue by SeekPoint** [zhaop93/bert-joint-NLU#3]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from utils import Joint_Processor
  File "/Users//nnlm_gen/bert-joint-NLU/utils.py", line 6, in <module>
    from bert import modeling, tokenization, optimization
ImportError: cannot import name 'modeling' from 'bert'

**Comment by xiaopp123** [comment]
这不是版本问题，引入包失败。创建一个bert文件夹，将github上bert的源文件下载到这个文件夹，保险的话，在bert文件夹创建一个__init__.py
