### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by dandan2020-ui** [zhaop93/bert-joint-NLU#5]
Traceback (most recent call last):
  File "E:/8、Chatbot机器人/nlu-master/sample_code/random_output.py", line 33, in <module>
    dev_dct = json.load(open(sys.argv[1]), encoding='utf8')
IndexError: list index out of range

**Comment by AIwjy94** [comment]
请问你解决了吗？我也遇到了这个问题

**Comment by AIwjy94** [comment]
> Traceback (most recent call last):
> File "E:/8、Chatbot机器人/nlu-master/sample_code/random_output.py", line 33, in
> dev_dct = json.load(open(sys.argv[1]), encoding='utf8')
> IndexError: list index out of range

请问你解决了吗？我也遇到这个问题
